# Site settings
title: A blog about zLeewack
description: A blog about zLeewack
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zhi Li
user_description: I am a computer vision master, where I work on visual slam and UAV navigation. I obtained my BSc and MSc from Northwestern Polytechnical University in 2012 and 2019 respectively, under the supervision of Prof. Tao Yang.
# user_title: computer vision
email: zLeewack@163.com
twitter_username: zLeewack
github_username:  zLeewack
gplus_username:  zLeewack


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
